version: '3.4'

services:
  solr:
    image: solr:7
    container_name: SolrService
    ports:
     - "8983:8983"
    volumes:
     - data:/var/solr
    entrypoint:
     - bash
     - "-c"
     - "precreate-core catalog-internal-index; precreate-core invoicingindex; exec solr -f"

  searchqueryservice:
    image: ${DOCKER_REGISTRY-}searchqueryservice
    build:
      context: ../src
      dockerfile: ../src/SearchQueryService/Dockerfile
    ports:
      - "8000:443"
      - "8001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    volumes:
      - "./indexes:/srv/demo"

  eshopdemo.api:
    image: ${DOCKER_REGISTRY-}eshopdemo.api
    build:
      context: .
      dockerfile: ./EshopDemo.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "7000:443"
      - "7001:80"

volumes:
  data:
